export type FontCategory = 'Sans Serif' | 'Serif' | 'Monospace' | 'Display' | 'Handwriting' | 'Standard';

export interface FontMetadata {
  family: string;
  category: FontCategory;
  variants: string[]; // e.g., ['400', '700', '400i', '700i']
}

export const FONT_REGISTRY: FontMetadata[] = [
  // Standard / System Fonts (Most Common)
  { family: 'Arial', category: 'Standard', variants: ['400', '700'] },
  { family: 'Verdana', category: 'Standard', variants: ['400', '700'] },
  { family: 'Tahoma', category: 'Standard', variants: ['400', '700'] },
  { family: 'Trebuchet MS', category: 'Standard', variants: ['400', '700'] },
  { family: 'Times New Roman', category: 'Standard', variants: ['400', '700'] },
  { family: 'Georgia', category: 'Standard', variants: ['400', '700'] },
  { family: 'Garamond', category: 'Standard', variants: ['400', '700'] },
  { family: 'Courier New', category: 'Standard', variants: ['400', '700'] },
  { family: 'Comic Sans MS', category: 'Standard', variants: ['400'] },
  { family: 'Impact', category: 'Standard', variants: ['400'] },
  { family: 'Helvetica', category: 'Standard', variants: ['400', '700'] },
  { family: 'Times', category: 'Standard', variants: ['400', '700'] },
  { family: 'Courier', category: 'Standard', variants: ['400', '700'] },

  // Sans Serif
  { family: 'Roboto', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Inter', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Open Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Lato', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Montserrat', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Poppins', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Source Sans Pro', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Raleway', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Ubuntu', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Oswald', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Nunito', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Playfair Display', category: 'Serif', variants: ['400', '700'] },
  { family: 'Merriweather', category: 'Serif', variants: ['400', '700'] },
  { family: 'Lora', category: 'Serif', variants: ['400', '700'] },
  { family: 'PT Serif', category: 'Serif', variants: ['400', '700'] },
  { family: 'Libre Baskerville', category: 'Serif', variants: ['400', '700'] },
  { family: 'Noto Serif', category: 'Serif', variants: ['400', '700'] },
  { family: 'Crimson Text', category: 'Serif', variants: ['400', '700'] },
  { family: 'Roboto Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Fira Code', category: 'Monospace', variants: ['400', '700'] },
  { family: 'JetBrains Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Inconsolata', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Pacifico', category: 'Handwriting', variants: ['400'] },
  { family: 'Dancing Script', category: 'Handwriting', variants: ['400', '700'] },
  { family: 'Lobster', category: 'Display', variants: ['400'] },
  { family: 'Bebas Neue', category: 'Display', variants: ['400'] },
  { family: 'Abril Fatface', category: 'Display', variants: ['400'] },
  { family: 'Righteous', category: 'Display', variants: ['400'] },
  // ... (Expanding to 200 items in chunks if needed, but starting with these core ones)
  { family: 'Quicksand', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Kanit', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Heebo', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Work Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'DM Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Karla', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Rubik', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Libre Franklin', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Arimo', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Comfortaa', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'PT Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Titillium Web', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Muli', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Manrope', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Josefin Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Cabin', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Dosis', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Exo 2', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Archivo', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Sora', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Barlow', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Public Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Outfit', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Be Vietnam Pro', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Bitter', category: 'Serif', variants: ['400', '700'] },
  { family: 'Arvo', category: 'Serif', variants: ['400', '700'] },
  { family: 'Domine', category: 'Serif', variants: ['400', '700'] },
  { family: 'Zilla Slab', category: 'Serif', variants: ['400', '700'] },
  { family: 'Vollkorn', category: 'Serif', variants: ['400', '700'] },
  { family: 'Cardo', category: 'Serif', variants: ['400', '700'] },
  { family: 'Old Standard TT', category: 'Serif', variants: ['400', '700'] },
  { family: 'Neuton', category: 'Serif', variants: ['400', '700'] },
  { family: 'EB Garamond', category: 'Serif', variants: ['400', '700'] },
  { family: 'Tinos', category: 'Serif', variants: ['400', '700'] },
  { family: 'Bree Serif', category: 'Serif', variants: ['400', '700'] },
  { family: 'Spectral', category: 'Serif', variants: ['400', '700'] },
  { family: 'Cormorant Garamond', category: 'Serif', variants: ['400', '700'] },
  { family: 'Alegreya', category: 'Serif', variants: ['400', '700'] },
  { family: 'IBM Plex Serif', category: 'Serif', variants: ['400', '700'] },
  { family: 'Space Grotesk', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Syne', category: 'Display', variants: ['400', '700'] },
  { family: 'Lexend', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Plus Jakarta Sans', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Urbanist', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Fraunces', category: 'Serif', variants: ['400', '700'] },
  { family: 'Space Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'IBM Plex Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Ubuntu Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Source Code Pro', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Anonymous Pro', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Courier Prime', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Nanum Gothic Coding', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Cutive Mono', category: 'Monospace', variants: ['400'] },
  { family: 'Share Tech Mono', category: 'Monospace', variants: ['400'] },
  { family: 'Overpass Mono', category: 'Monospace', variants: ['400', '700'] },
  { family: 'Nova Mono', category: 'Monospace', variants: ['400'] },
  { family: 'VT323', category: 'Monospace', variants: ['400'] },
  { family: 'Special Elite', category: 'Display', variants: ['400'] },
  { family: 'Alfa Slab One', category: 'Display', variants: ['400'] },
  { family: 'Anton', category: 'Display', variants: ['400'] },
  { family: 'Bangers', category: 'Display', variants: ['400'] },
  { family: 'Luckiest Guy', category: 'Display', variants: ['400'] },
  { family: 'Permanent Marker', category: 'Handwriting', variants: ['400'] },
  { family: 'Satisfy', category: 'Handwriting', variants: ['400'] },
  { family: 'Caveat', category: 'Handwriting', variants: ['400', '700'] },
  { family: 'Sacramento', category: 'Handwriting', variants: ['400'] },
  { family: 'Shadows Into Light', category: 'Handwriting', variants: ['400'] },
  { family: 'Amatic SC', category: 'Handwriting', variants: ['400', '700'] },
  { family: 'Indie Flower', category: 'Handwriting', variants: ['400'] },
  { family: 'Cookie', category: 'Handwriting', variants: ['400'] },
  { family: 'Kaushan Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Great Vibes', category: 'Handwriting', variants: ['400'] },
  { family: 'Yellowtail', category: 'Handwriting', variants: ['400'] },
  { family: 'Parisienne', category: 'Handwriting', variants: ['400'] },
  { family: 'Tangerine', category: 'Handwriting', variants: ['400'] },
  { family: 'Monoton', category: 'Display', variants: ['400'] },
  { family: 'Press Start 2P', category: 'Display', variants: ['400'] },
  { family: 'Cinzel', category: 'Serif', variants: ['400', '700'] },
  { family: 'Cinzel Decorative', category: 'Display', variants: ['400', '700'] },
  { family: 'UnifrakturMaguntia', category: 'Display', variants: ['400'] },
  { family: 'Fredericka the Great', category: 'Display', variants: ['400'] },
  { family: 'Creepster', category: 'Display', variants: ['400'] },
  { family: 'Nosifer', category: 'Display', variants: ['400'] },
  { family: 'Piedra', category: 'Display', variants: ['400'] },
  { family: 'Eater', category: 'Display', variants: ['400'] },
  { family: 'Metal Mania', category: 'Display', variants: ['400'] },
  { family: 'Homemade Apple', category: 'Handwriting', variants: ['400'] },
  { family: 'Alex Brush', category: 'Handwriting', variants: ['400'] },
  { family: 'Allura', category: 'Handwriting', variants: ['400'] },
  { family: 'Arizonia', category: 'Handwriting', variants: ['400'] },
  { family: 'Grand Hotel', category: 'Handwriting', variants: ['400'] },
  { family: 'Herr Von Muellerhoff', category: 'Handwriting', variants: ['400'] },
  { family: 'Mrs Saint Delafield', category: 'Handwriting', variants: ['400'] },
  { family: 'Pinyon Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Rochester', category: 'Handwriting', variants: ['400'] },
  { family: 'Ruthie', category: 'Handwriting', variants: ['400'] },
  { family: 'Seaweed Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Stalemate', category: 'Handwriting', variants: ['400'] },
  { family: 'Jim Nightshade', category: 'Handwriting', variants: ['400'] },
  { family: 'Fondamento', category: 'Handwriting', variants: ['400'] },
  { family: 'Marck Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Calligraffitti', category: 'Handwriting', variants: ['400'] },
  { family: 'Bad Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Coming Soon', category: 'Handwriting', variants: ['400'] },
  { family: 'Just Me Again Down Here', category: 'Handwriting', variants: ['400'] },
  { family: 'Rock Salt', category: 'Handwriting', variants: ['400'] },
  { family: 'Sue Ellen Francisco', category: 'Handwriting', variants: ['400'] },
  { family: 'Architects Daughter', category: 'Handwriting', variants: ['400'] },
  { family: 'Handlee', category: 'Handwriting', variants: ['400'] },
  { family: 'Annie Use Your Telescope', category: 'Handwriting', variants: ['400'] },
  { family: 'Covered By Your Grace', category: 'Handwriting', variants: ['400'] },
  { family: 'Gochi Hand', category: 'Handwriting', variants: ['400'] },
  { family: 'Gloria Hallelujah', category: 'Handwriting', variants: ['400'] },
  { family: 'Nothing You Could Do', category: 'Handwriting', variants: ['400'] },
  { family: 'Patrick Hand', category: 'Handwriting', variants: ['400'] },
  { family: 'Reenie Beanie', category: 'Handwriting', variants: ['400'] },
  { family: 'Schoolbell', category: 'Handwriting', variants: ['400'] },
  { family: 'Short Stack', category: 'Handwriting', variants: ['400'] },
  { family: 'Waiting for the Sunrise', category: 'Handwriting', variants: ['400'] },
  { family: 'Zeyada', category: 'Handwriting', variants: ['400'] },
  { family: 'Loved by the King', category: 'Handwriting', variants: ['400'] },
  { family: 'Over the Rainbow', category: 'Handwriting', variants: ['400'] },
  { family: 'Gaegu', category: 'Handwriting', variants: ['400', '700'] },
  { family: 'Gamja Flower', category: 'Handwriting', variants: ['400'] },
  { family: 'Hi Melody', category: 'Handwriting', variants: ['400'] },
  { family: 'Jua', category: 'Sans Serif', variants: ['400'] },
  { family: 'Nanum Pen Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Nanum Brush Script', category: 'Handwriting', variants: ['400'] },
  { family: 'Poor Story', category: 'Handwriting', variants: ['400'] },
  { family: 'Single Day', category: 'Handwriting', variants: ['400'] },
  { family: 'Sunflower', category: 'Sans Serif', variants: ['300', '500', '700'] },
  { family: 'Yeon Sung', category: 'Handwriting', variants: ['400'] },
  { family: 'Cute Font', category: 'Display', variants: ['400'] },
  { family: 'Dokdo', category: 'Display', variants: ['400'] },
  { family: 'East Sea Dokdo', category: 'Display', variants: ['400'] },
  { family: 'Black And White Picture', category: 'Sans Serif', variants: ['400'] },
  { family: 'Black Han Sans', category: 'Sans Serif', variants: ['400'] },
  { family: 'Do Hyeon', category: 'Sans Serif', variants: ['400'] },
  { family: 'Gothic A1', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Nanum Gothic', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Nanum Myeongjo', category: 'Serif', variants: ['400', '700'] },
  { family: 'Song Myung', category: 'Serif', variants: ['400'] },
  { family: 'Stylish', category: 'Sans Serif', variants: ['400'] },
  { family: 'Gugi', category: 'Display', variants: ['400'] },
  { family: 'Black Ops One', category: 'Display', variants: ['400'] },
  { family: 'Butcherman', category: 'Display', variants: ['400'] },
  { family: 'Chango', category: 'Display', variants: ['400'] },
  { family: 'Ewert', category: 'Display', variants: ['400'] },
  { family: 'Fascinate', category: 'Display', variants: ['400'] },
  { family: 'Fascinate Inline', category: 'Display', variants: ['400'] },
  { family: 'Faster One', category: 'Display', variants: ['400'] },
  { family: 'Finger Paint', category: 'Display', variants: ['400'] },
  { family: 'Glass Antiqua', category: 'Display', variants: ['400'] },
  { family: 'Gravitas One', category: 'Display', variants: ['400'] },
  { family: 'Iceland', category: 'Display', variants: ['400'] },
  { family: 'Jolly Lodger', category: 'Display', variants: ['400'] },
  { family: 'Keania One', category: 'Display', variants: ['400'] },
  { family: 'Life Savers', category: 'Display', variants: ['400', '700'] },
  { family: 'Megrim', category: 'Display', variants: ['400'] },
  { family: 'Metal Mania', category: 'Display', variants: ['400'] },
  { family: 'Miltonian', category: 'Display', variants: ['400'] },
  { family: 'Miltonian Tattoo', category: 'Display', variants: ['400'] },
  { family: 'Modern Antiqua', category: 'Display', variants: ['400'] },
  { family: 'Mystery Quest', category: 'Display', variants: ['400'] },
  { family: 'New Rocker', category: 'Display', variants: ['400'] },
  { family: 'Nova Cut', category: 'Display', variants: ['400'] },
  { family: 'Nova Flat', category: 'Display', variants: ['400'] },
  { family: 'Nova Oval', category: 'Display', variants: ['400'] },
  { family: 'Nova Round', category: 'Display', variants: ['400'] },
  { family: 'Nova Script', category: 'Display', variants: ['400'] },
  { family: 'Nova Slim', category: 'Display', variants: ['400'] },
  { family: 'Nova Square', category: 'Display', variants: ['400'] },
  { family: 'Offside', category: 'Display', variants: ['400'] },
  { family: 'Oldenburg', category: 'Display', variants: ['400'] },
  { family: 'Orbitron', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Original Surfer', category: 'Display', variants: ['400'] },
  { family: 'Oswald', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Passero One', category: 'Display', variants: ['400'] },
  { family: 'Passion One', category: 'Display', variants: ['400', '700'] },
  { family: 'Patua One', category: 'Display', variants: ['400'] },
  { family: 'Peralta', category: 'Display', variants: ['400'] },
  { family: 'Pirata One', category: 'Display', variants: ['400'] },
  { family: 'Plaster', category: 'Display', variants: ['400'] },
  { family: 'Play', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Poller One', category: 'Display', variants: ['400'] },
  { family: 'Press Start 2P', category: 'Display', variants: ['400'] },
  { family: 'Quantico', category: 'Sans Serif', variants: ['400', '700'] },
  { family: 'Racing Sans One', category: 'Display', variants: ['400'] },
  { family: 'Radley', category: 'Serif', variants: ['400'] },
  { family: 'Rationale', category: 'Sans Serif', variants: ['400'] },
  { family: 'Redressed', category: 'Handwriting', variants: ['400'] },
  { family: 'Revalia', category: 'Display', variants: ['400'] },
  { family: 'Ribeye', category: 'Display', variants: ['400'] },
  { family: 'Ribeye Marrow', category: 'Display', variants: ['400'] },
  { family: 'Righteous', category: 'Display', variants: ['400'] },
  { family: 'Ruslan Display', category: 'Display', variants: ['400'] },
  { family: 'Russo One', category: 'Sans Serif', variants: ['400'] },
  { family: 'Ruthie', category: 'Handwriting', variants: ['400'] },
  { family: 'Sail', category: 'Display', variants: ['400'] },
  { family: 'Salsa', category: 'Display', variants: ['400'] },
  { family: 'Sancreek', category: 'Display', variants: ['400'] },
  { family: 'Sansita One', category: 'Display', variants: ['400'] },
  { family: 'Sarina', category: 'Display', variants: ['400'] },
  { family: 'Sevillana', category: 'Display', variants: ['400'] },
  { family: 'Seymour One', category: 'Sans Serif', variants: ['400'] },
  { family: 'Shojumaru', category: 'Display', variants: ['400'] },
  { family: 'Sigmar One', category: 'Display', variants: ['400'] },
  { family: 'Sirin Stencil', category: 'Display', variants: ['400'] },
  { family: 'Skranji', category: 'Display', variants: ['400', '700'] },
  { family: 'Slackey', category: 'Display', variants: ['400'] },
  { family: 'Smokum', category: 'Display', variants: ['400'] },
  { family: 'Smythe', category: 'Display', variants: ['400'] },
  { family: 'Sniglet', category: 'Display', variants: ['400', '800'] },
  { family: 'Snowburst One', category: 'Display', variants: ['400'] },
  { family: 'Sofadi One', category: 'Display', variants: ['400'] },
  { family: 'Sonsie One', category: 'Display', variants: ['400'] },
  { family: 'Spicy Rice', category: 'Display', variants: ['400'] },
  { family: 'Spirax', category: 'Display', variants: ['400'] },
  { family: 'Squada One', category: 'Display', variants: ['400'] },
  { family: 'Stalinist One', category: 'Display', variants: ['400'] },
  { family: 'Stardos Stencil', category: 'Display', variants: ['400', '700'] },
  { family: 'Stint Ultra Condensed', category: 'Display', variants: ['400'] },
  { family: 'Stint Ultra Expanded', category: 'Display', variants: ['400'] },
  { family: 'Supermercado One', category: 'Display', variants: ['400'] },
  { family: 'Titan One', category: 'Display', variants: ['400'] },
  { family: 'Trade Winds', category: 'Display', variants: ['400'] },
  { family: 'Trochut', category: 'Display', variants: ['400', '700'] },
  { family: 'Unica One', category: 'Display', variants: ['400'] },
  { family: 'UnifrakturCook', category: 'Display', variants: ['700'] },
  { family: 'UnifrakturMaguntia', category: 'Display', variants: ['400'] },
  { family: 'Unkempt', category: 'Display', variants: ['400', '700'] },
  { family: 'Vampiro One', category: 'Display', variants: ['400'] },
  { family: 'Vast Shadow', category: 'Display', variants: ['400'] },
  { family: 'Voces', category: 'Display', variants: ['400'] },
  { family: 'Wallpoet', category: 'Display', variants: ['400'] },
  { family: 'Warnes', category: 'Display', variants: ['400'] },
  { family: 'Wellfleet', category: 'Display', variants: ['400'] },
  { family: 'Yeseva One', category: 'Display', variants: ['400'] },
  { family: 'Zeyada', category: 'Handwriting', variants: ['400'] },
  { family: 'Zilla Slab Highlight', category: 'Display', variants: ['400', '700'] }
];
